---
functional:
  - создание раздельного экрана для реального времени
  - минимальная задержка при синхронизации кода
  - поддержка популярных языков: Python, JavaScript и PHP
  - наличие набора задач разного уровня сложности 
  - наличие общего таймера на решение задачи,отображаемый для обоих участников 
  - наличие встроенного текстового чата для общения в рамках комнаты 
non-functional:
  - система должна быть доступна сто процентов времени 
  - при разрыве соединения код должен автоматически сохраняться, а сессия- восстанавливаться без потери данных 
  - система должна предотвращать попытки копирования кода у окна соперника с помощью контекстного меню 
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - если у одного из участника пропадает связь,	соревнование должно становиться на паузу, а не засчитывать автоматическое поражение
  - удобное расположение окон ( слева-код мой, справа- код соперника)
  - код,написанный первым программистом, должен появляться у второго с задежкой, равной нулю, чтобюы исключить нессправедливое преимущество
